# Site settings
name: mturing
email: mturing@163.com
author: tangc
url: http://www.mturing.top
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/mturing
baseurl: ""
description: Actually, less is more!
meta_description: tangc;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Some Interesting things are happing!!!
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: mturing
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light